version: '2'

services: 
  l5d:
    image: buoyantio/linkerd:0.8.6
    ports:
    - "4140:4140"
    - "4142:4142"
    - "9990:9990"
    # we must mount the config file and the disco directory
    volumes:
    - ./linkerd.yaml:/io.buoyant/linkerd.yaml:ro
    - ./disco:/io.buoyant/disco
    command: >
      /io.buoyant/linkerd.yaml
    restart: unless-stopped

  namerd:
    image: buoyantio/namerd:0.8.6
    ports:
      - "4180:4180"
      - "4100:4100"
      - "9991:9991"
    volumes:
    - ./namerd.yaml:/io.buoyant/namerd.yaml:ro
    - ./disco:/io.buoyant/disco
    command: >
      /io.buoyant/namerd.yaml
      -com.twitter.finagle.tracing.debugTrace=true
      -log.level=DEBUG

  hello:
    build: .
    environment: 
      - HTTP_PROXY=l5d:4140
      - NAMERCTL_BASE_URL=http://namerd
    command: bash -c "namerctl dtab update default service.dtab && greeter_server"
    restart: unless-stopped